# Generated by Django 5.0.8 on 2024-08-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='unique_code',
            new_name='unique_key',
        ),
    ]
