# Generated by Django 5.0.8 on 2024-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_unique_code_purchase_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unique_key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
