# Generated by Django 5.0.8 on 2024-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_app_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='app_link',
        ),
    ]
