# Generated by Django 5.0.8 on 2024-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
