# Generated by Django 5.0.8 on 2024-08-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_app_app_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="app_link",
        ),
    ]
